name: Testes de API e Relatório

on:
  push:
    branches: [main]

jobs:
  test-api:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Executar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - run: npm install

    - run: npm test  

    - name: Enviar relatório 
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./newman
