name: Testes de API e Relatório

on:
  push:
    branches: [main]

jobs:
  test-api:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3

    - name: Executar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - run: npm install --legacy-peer-deps 

    - run: npm test  

    - name: Enviar relatório 
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./mochawesome-report
        destination_dir: .
        keep_files: true  
